"""
O2 Data Solutions — Email Data Module
Dados completos para templates de email: labels, ícones, recomendações.
"""

AREA_LABELS = {
    "supply_chain":  "Supply Chain & Compras",
    "comercial":     "Inteligência Comercial & RevOps",
    "credito_risco": "Crédito & Risco",
    "dados_ml":      "Dados & Machine Learning",
    "automacao":     "Automação, RPA & Alertas",
    "dashboards":    "Dashboards & Analytics",
}

AREA_ICONS_EMOJI = {
    "supply_chain":  "🚚",
    "comercial":     "📈",
    "credito_risco": "🛡️",
    "dados_ml":      "🧠",
    "automacao":     "🤖",
    "dashboards":    "📊",
}

AREA_COLORS = {
    "supply_chain":  "#3b82f6",
    "comercial":     "#8b5cf6",
    "credito_risco": "#ef4444",
    "dados_ml":      "#06b6d4",
    "automacao":     "#f59e0b",
    "dashboards":    "#22c55e",
}

# Mapeamento question_id -> label legível
QUESTION_LABELS = {
    # Supply Chain & Compras
    "sc_01": "Previsão de demanda",
    "sc_02": "Visibilidade de estoque em tempo real",
    "sc_03": "Planejamento de compras e reposição",
    "sc_04": "Integração de dados com fornecedores",
    "sc_05": "Monitoramento de desempenho de fornecedores",
    "sc_06": "Controle do custo total de aquisição (TCO)",
    "sc_07": "Gestão de rupturas de estoque",
    "sc_08": "Análise de sazonalidade e tendências",
    "sc_09": "Estoque de segurança e giro de estoque",
    "sc_10": "Rastreabilidade de produtos na cadeia",
    "sc_11": "Otimização de custos logísticos",
    "sc_12": "Automação de cotação e negociação",
    "sc_13": "Medição e redução de lead time",
    "sc_14": "Análise de risco na cadeia de suprimentos",
    "sc_15": "Uso de dados em negociação com fornecedores",
    "sc_16": "Integração Supply Chain x Comercial (S&OP)",
    "sc_17": "Gestão de produtos obsoletos / baixo giro",
    "sc_18": "Analytics para otimização do mix de produtos",
    "sc_19": "Controle de qualidade de recebimento",
    "sc_20": "Maturidade do processo S&OP",
    "sc_21": "Impacto financeiro das decisões de estoque",
    "sc_22": "Uso de dados externos no planejamento",
    # Inteligência Comercial & RevOps
    "com_01": "Monitoramento e análise do funil de vendas",
    "com_02": "Segmentação de clientes baseada em dados",
    "com_03": "Medição do CAC por canal",
    "com_04": "Análise do Lifetime Value (LTV)",
    "com_05": "Identificação de cross-sell e upsell",
    "com_06": "Previsão de receita (forecast de vendas)",
    "com_07": "Análise e redução do churn",
    "com_08": "Integração CRM x Marketing x Financeiro",
    "com_09": "Medição do ROI de campanhas de marketing",
    "com_10": "Personalização das abordagens comerciais",
    "com_11": "Análise de performance do time de vendas",
    "com_12": "Análise de precificação e elasticidade",
    "com_13": "Identificação e priorização de leads",
    "com_14": "Análise do ciclo de vendas e fechamento",
    "com_15": "Monitoramento de satisfação e NPS",
    "com_16": "Inteligência competitiva e de mercado",
    "com_17": "Rentabilidade por cliente, produto e canal",
    "com_18": "Automação de follow-up e nutrição de leads",
    "com_19": "Definição de territórios e cotas por dados",
    "com_20": "Análise de cohort e retenção de clientes",
    "com_21": "Velocidade e otimização do pipeline",
    "com_22": "Expansão em novos mercados por dados",
    # Crédito & Risco
    "cr_01": "Análise de crédito para novos clientes",
    "cr_02": "Automação no processo de concessão de crédito",
    "cr_03": "Monitoramento do risco da carteira",
    "cr_04": "Modelos preditivos de inadimplência",
    "cr_05": "Segmentação e priorização da régua de cobrança",
    "cr_06": "Análise de fraude em crédito e pagamento",
    "cr_07": "Cálculo e monitoramento de provisões (PDD)",
    "cr_08": "Integração dados de crédito x operacional",
    "cr_09": "Análise e otimização do limite de crédito",
    "cr_10": "Análise de concentração de risco na carteira",
    "cr_11": "Eficiência e custo do processo de cobrança",
    "cr_12": "Uso de dados alternativos na análise de crédito",
    "cr_13": "Gestão do risco de contraparte B2B",
    "cr_14": "Automação nos processos de recuperação de crédito",
    "cr_15": "Análise do impacto das políticas de crédito",
    "cr_16": "Conformidade e auditabilidade dos processos",
    "cr_17": "Monitoramento do risco operacional financeiro",
    "cr_18": "Análise de vintage e safra da carteira",
    "cr_19": "Precificação baseada em risco de crédito",
    "cr_20": "Monitoramento de variáveis macroeconômicas",
    "cr_21": "Gestão do risco de liquidez e fluxo de caixa",
    # Dados & Machine Learning
    "ml_01": "Qualidade e confiabilidade dos dados",
    "ml_02": "Centralização e integração das fontes de dados",
    "ml_03": "Governança e catálogo de dados",
    "ml_04": "Modelos de Machine Learning em produção",
    "ml_05": "Gestão do ciclo de vida dos modelos (MLOps)",
    "ml_06": "Maturidade da infraestrutura de dados",
    "ml_07": "Privacidade e segurança dos dados (LGPD/GDPR)",
    "ml_08": "Democratização do acesso a dados",
    "ml_09": "Monitoramento de performance dos modelos de ML",
    "ml_10": "Uso de IA generativa e LLMs nos processos",
    "ml_11": "Gestão e documentação de experimentos",
    "ml_12": "Capacitação da equipe em dados e analytics",
    "ml_13": "Explicabilidade e interpretabilidade (XAI)",
    "ml_14": "Automação dos pipelines de dados (ETL/ELT)",
    "ml_15": "Medição do ROI dos projetos de dados e ML",
    "ml_16": "Uso de dados em tempo real (streaming)",
    "ml_17": "Estratégia de dados e roadmap analítico",
    "ml_18": "Feature stores e reutilização de features",
    "ml_19": "Testes e validação de modelos antes de produção",
    "ml_20": "Integração entre dados e sistemas de decisão",
    "ml_21": "Cultura data-driven na organização",
    # Automação, RPA & Alertas
    "aut_01": "Percentual de processos repetitivos automatizados",
    "aut_02": "Identificação de oportunidades de automação",
    "aut_03": "Automação na geração e distribuição de relatórios",
    "aut_04": "Gestão e monitoramento de robôs em produção",
    "aut_05": "Automação de integrações entre sistemas (APIs/ETL)",
    "aut_06": "Alertas inteligentes para KPIs críticos",
    "aut_07": "Automação em cobrança e comunicação com clientes",
    "aut_08": "Automação de coleta e consolidação de dados",
    "aut_09": "Uso de chatbots e assistentes virtuais",
    "aut_10": "Automação do processo de precificação",
    "aut_11": "Automação em processos de compras e aprovações",
    "aut_12": "Monitoramento e alertas de anomalias em dados",
    "aut_13": "Automação em processos de RH",
    "aut_14": "Automação no monitoramento de concorrentes",
    "aut_15": "Automação em faturamento e conciliação financeira",
    "aut_16": "Gestão e documentação de processos automatizados",
    "aut_17": "Automação no onboarding de clientes e parceiros",
    "aut_18": "Medição do ROI e ganhos de produtividade",
    "aut_19": "Automação em processos de compliance e auditoria",
    "aut_20": "Uso de automação para melhorar a experiência do cliente",
    "aut_21": "Integração entre automações e sistemas de BI/Analytics",
    # Dashboards & Analytics
    "dash_01": "Qualidade e usabilidade dos dashboards",
    "dash_02": "Atualização e frequência dos dados",
    "dash_03": "Alinhamento dos KPIs com prioridades estratégicas",
    "dash_04": "Nível de self-service analytics",
    "dash_05": "Medição de adoção e uso dos dashboards",
    "dash_06": "Análise exploratória e descoberta de insights",
    "dash_07": "Gestão do ciclo de vida de relatórios e dashboards",
    "dash_08": "Análise preditiva e prescritiva nos dashboards",
    "dash_09": "Consistência e confiabilidade das métricas",
    "dash_10": "Personalização dos dashboards por perfil de usuário",
    "dash_11": "Storytelling com dados para stakeholders",
    "dash_12": "Análise de causa raiz (root cause analysis)",
    "dash_13": "Analytics de experiência do cliente (CX)",
    "dash_14": "Análise de benchmarking interno e externo",
    "dash_15": "Análise de cohort e segmentação avançada",
    "dash_16": "Análise geoespacial e territorial",
    "dash_17": "Gestão e análise de dados não estruturados",
    "dash_18": "Análise de simulação e cenários (what-if)",
    "dash_19": "Medição de produtividade e eficiência operacional",
    "dash_20": "Integração entre analytics e tomada de decisão",
    "dash_21": "Acessibilidade e disponibilidade dos dashboards",
    "dash_22": "Análise de atribuição e impacto das iniciativas",
}

RECOMMENDATIONS = {
    "supply_chain": {
        "critico": [
            "Implemente controle de estoque com alertas automáticos de ruptura para os 20% de SKUs críticos (Pareto ABC).",
            "Crie previsão de demanda baseada em histórico dos últimos 12 meses — mesmo uma planilha estruturada já reduz compras por urgência em 30%.",
            "Estabeleça KPIs básicos monitorados semanalmente: giro de estoque, cobertura em dias e taxa de ruptura.",
            "Automatize cotação com pelo menos 3 fornecedores por item crítico para reduzir TCO e dependência de fornecedor único.",
            "Defina política de estoque de segurança com ponto de pedido para os itens de maior impacto no faturamento.",
            "Implemente análise ABC-XYZ para priorizar esforços de gestão e reduzir capital imobilizado em itens de baixo giro.",
        ],
        "desenvolvimento": [
            "Evolua para modelos estatísticos de previsão de demanda (suavização exponencial, decomposição de série temporal) integrados ao ERP.",
            "Automatize o processo de reposição com ponto de pedido dinâmico baseado em variabilidade de demanda e lead time real.",
            "Integre dados de fornecedores via API/EDI para visibilidade em tempo real e redução de lead time de compras.",
            "Implemente scorecard automatizado de fornecedores com KPIs de prazo, qualidade e preço para embasar negociações.",
            "Desenvolva análise de TCO completo (preço + frete + armazenagem + obsolescência) para decisões de compra mais estratégicas.",
            "Implemente S&OP integrado com dados em tempo real e planejamento colaborativo entre Supply Chain e Comercial.",
        ],
        "avancado": [
            "Implemente modelos de ML para previsão de demanda com variáveis externas (clima, câmbio, commodities, tendências de mercado).",
            "Desenvolva digital twin da cadeia de suprimentos para simulações de cenários e otimização de rede logística.",
            "Explore IoT/RFID para rastreabilidade end-to-end em tempo real com alertas preditivos antes de rupturas.",
            "Implemente análise de risco quantitativa com stress tests automatizados e planos de contingência dinâmicos.",
            "Explore IA generativa para otimização de contratos, negociações e análise de cláusulas com fornecedores.",
            "Desenvolva S&OP avançado com simulação de cenários, otimização de portfólio e decisões baseadas em rentabilidade.",
        ],
    },
    "comercial": {
        "critico": [
            "Implemente CRM básico para estruturar o funil de vendas e ter visibilidade das oportunidades — sem dados, não há gestão.",
            "Calcule CAC e LTV médio da base atual: saber quanto custa adquirir e quanto vale cada cliente é o ponto de partida.",
            "Crie dashboard com funil de vendas, taxa de conversão por etapa e ciclo médio — identifique onde os leads estão travando.",
            "Defina processo de qualificação de leads com critérios objetivos (BANT) para o time focar nos de maior potencial.",
            "Estabeleça régua de follow-up automatizada para leads não convertidos — 80% das vendas acontecem após o 5º contato.",
            "Meça a taxa de churn mensal e identifique os 3 principais motivos de saída para agir preventivamente.",
        ],
        "desenvolvimento": [
            "Implemente lead scoring automático baseado em comportamento e perfil para priorizar esforços do time comercial.",
            "Desenvolva modelos de propensão de churn e cross-sell com ML para intervenção proativa antes da perda.",
            "Crie análise de cohort para entender retenção e LTV por segmento, canal e período de aquisição.",
            "Automatize nutrição de leads com sequências personalizadas e gatilhos comportamentais integrados ao CRM.",
            "Implemente atribuição multi-touch para medir ROI real por canal de marketing e otimizar o mix de investimento.",
            "Desenvolva análise de rentabilidade por cliente, produto e canal para focar nos segmentos mais lucrativos.",
        ],
        "avancado": [
            "Implemente personalização em escala com IA generativa no conteúdo comercial, propostas e comunicações.",
            "Desenvolva precificação dinâmica com análise de elasticidade e otimização de margem por segmento e contexto.",
            "Explore revenue intelligence com análise de conversas e e-mails de vendas para identificar padrões de sucesso.",
            "Implemente análise de sentimento em tempo real para monitorar satisfação e agir antes do churn.",
            "Desenvolva modelos de expansão de mercado com análise de potencial geoespacial e whitespace analysis.",
            "Implemente decision intelligence com recomendações prescritivas automáticas no pipeline de vendas.",
        ],
    },
    "credito_risco": {
        "critico": [
            "Implemente processo formal de análise de crédito com consulta a bureaus e critérios documentados para todos os novos clientes.",
            "Crie régua de cobrança básica com comunicações automáticas por e-mail/SMS para diferentes faixas de atraso (1-15, 16-30, 31-60 dias).",
            "Defina políticas de limite de crédito por perfil de cliente com revisão semestral baseada em comportamento de pagamento.",
            "Calcule inadimplência por faixa de atraso e defina metas de redução — o que não é medido não é gerenciado.",
            "Implemente processo de análise de fraude para operações acima de um threshold definido por risco.",
            "Documente e automatize o processo de aprovação de crédito com alçadas definidas por valor e risco.",
        ],
        "desenvolvimento": [
            "Desenvolva scorecard de crédito com variáveis comportamentais e financeiras para decisões mais precisas e consistentes.",
            "Implemente modelo preditivo de inadimplência para intervenção proativa antes do vencimento — reduza PDD com antecipação.",
            "Automatize régua de cobrança com segmentação por perfil de risco e canal preferencial de comunicação.",
            "Implemente análise de vintage para identificar padrões de safra e ajustar políticas de concessão.",
            "Desenvolva análise de concentração de risco com limites automáticos por setor, região e cliente.",
            "Implemente detecção de fraude em tempo real com análise comportamental e regras dinâmicas.",
        ],
        "avancado": [
            "Implemente modelos de perda esperada (ECL/IFRS 9) para provisões dinâmicas e mais precisas.",
            "Desenvolva detecção de fraude com ML e análise comportamental avançada em tempo real.",
            "Implemente precificação baseada em risco (risk-based pricing) com modelos de perda esperada por segmento.",
            "Desenvolva stress tests automatizados com cenários macroeconômicos e impacto quantificado na carteira.",
            "Implemente XAI (Explicabilidade de IA) nos modelos de crédito para conformidade regulatória e auditoria.",
            "Explore dados alternativos e open banking para ampliar o acesso ao crédito com menor risco.",
        ],
    },
    "dados_ml": {
        "critico": [
            "Faça inventário completo de todas as fontes de dados da empresa — você não pode gerenciar o que não conhece.",
            "Implemente processo básico de qualidade de dados para as fontes críticas: validação, deduplicação e padronização.",
            "Centralize os dados em um repositório único (data warehouse simples) com atualização diária automatizada.",
            "Defina glossário de métricas para garantir consistência entre áreas — 'receita' significa a mesma coisa para todos?",
            "Treine a equipe em análise de dados básica com ferramentas acessíveis (Power BI, Python, SQL).",
            "Estabeleça processo de backup e recuperação de dados críticos — dados perdidos são oportunidades perdidas.",
        ],
        "desenvolvimento": [
            "Implemente data warehouse moderno com camadas bronze/silver/gold e governança de dados estruturada.",
            "Desenvolva pipelines de dados automatizados com orquestração (Airflow/Prefect) e monitoramento de qualidade.",
            "Coloque 2-3 modelos de ML em produção com monitoramento de performance e alertas de drift.",
            "Estabeleça processo de MLOps com CI/CD para modelos, versionamento e retreinamento automatizado.",
            "Implemente data catalog com linhagem, ownership e políticas de acesso por perfil.",
            "Democratize o acesso a dados com ferramentas de self-service analytics e treinamento da equipe.",
        ],
        "avancado": [
            "Explore arquitetura de data mesh para descentralização com governança centralizada e domínios de dados.",
            "Implemente feature store centralizado para reutilização de features entre modelos e redução de retrabalho.",
            "Desenvolva plataforma de IA generativa interna com RAG sobre dados proprietários para decisões mais rápidas.",
            "Implemente análise causal para decisões de negócio mais robustas — correlação não é causalidade.",
            "Desenvolva modelos de foundation especializados no domínio do negócio para vantagem competitiva sustentável.",
            "Implemente streaming analytics para casos de uso que exigem dados e decisões em tempo real.",
        ],
    },
    "automacao": {
        "critico": [
            "Mapeie os 5 processos mais repetitivos e calcule o tempo gasto por semana — priorize por ROI e facilidade de automação.",
            "Automatize a geração e envio dos relatórios mais acessados — libere horas do time para análise, não para montagem.",
            "Implemente alertas básicos por e-mail para KPIs críticos fora do limite — reatividade começa com visibilidade.",
            "Crie integrações simples entre os sistemas mais usados (ERP, CRM, planilhas) para eliminar retrabalho de digitação.",
            "Estabeleça processo de identificação e priorização de automações por ROI esperado e complexidade.",
            "Documente todos os processos manuais como pré-requisito para automação — você não automatiza o que não entende.",
        ],
        "desenvolvimento": [
            "Implemente RPA para os processos de maior volume e menor variabilidade (entrada de dados, conciliações, relatórios).",
            "Desenvolva detecção de anomalias com ML para alertas inteligentes e monitoramento proativo de KPIs.",
            "Automatize o processo de onboarding de clientes com validações automáticas e comunicações personalizadas.",
            "Implemente chatbot com IA para atendimento de primeiro nível — reduza volume de chamados e melhore CX.",
            "Crie framework de medição de ROI para todas as automações implementadas — prove o valor gerado.",
            "Desenvolva orquestração centralizada de robôs com monitoramento em tempo real e alertas de falha.",
        ],
        "avancado": [
            "Implemente hyperautomation combinando RPA, IA e process mining para automação inteligente de ponta a ponta.",
            "Desenvolva agentes de IA autônomos para processos de decisão complexos com supervisão humana.",
            "Explore automação cognitiva com processamento de linguagem natural para documentos e comunicações.",
            "Implemente orquestração inteligente de processos com aprendizado contínuo e otimização automática.",
            "Desenvolva plataforma de automação self-service para usuários de negócio sem necessidade de TI.",
            "Explore agentic AI para automação de workflows complexos e multi-etapas com raciocínio autônomo.",
        ],
    },
    "dashboards": {
        "critico": [
            "Defina os 5-10 KPIs mais críticos do negócio e crie dashboards simples e confiáveis — menos é mais.",
            "Implemente ferramenta de BI (Power BI, Tableau ou Metabase) para substituir relatórios em planilhas manuais.",
            "Garanta uma fonte única de verdade para as métricas mais importantes — elimine inconsistências entre áreas.",
            "Crie processo de atualização diária automática dos dashboards principais — dados desatualizados são perigosos.",
            "Treine os gestores no uso básico dos dashboards para tomada de decisão baseada em dados.",
            "Estabeleça reuniões semanais de revisão de métricas com a liderança para criar cultura data-driven.",
        ],
        "desenvolvimento": [
            "Evolua para dashboards interativos com drill-down, filtros e análise exploratória self-service.",
            "Implemente análise de tendências e alertas automáticos quando KPIs saem dos limites esperados.",
            "Desenvolva dashboards personalizados por perfil de usuário (CEO, gerentes, operacional) com visões relevantes.",
            "Implemente analytics de uso dos dashboards para identificar o que é mais utilizado e o que pode ser descontinuado.",
            "Desenvolva storytelling com dados para comunicar insights de forma clara e orientada à ação para stakeholders.",
            "Implemente análise de causa raiz automatizada para desvios de KPIs — identifique o porquê, não só o quê.",
        ],
        "avancado": [
            "Implemente análise preditiva e prescritiva integrada aos dashboards para antecipar problemas e recomendar ações.",
            "Desenvolva análise de simulação e cenários (what-if) para suporte à decisão estratégica em tempo real.",
            "Implemente análise geoespacial avançada para otimização territorial e identificação de oportunidades de mercado.",
            "Desenvolva modelos de atribuição causal para medir o impacto real das iniciativas de negócio.",
            "Implemente decision intelligence com dados integrados em todos os processos de decisão da organização.",
            "Explore IA generativa para geração automática de insights, narrativas e recomendações nos dashboards.",
        ],
    },
}