"""
O2 Data Solutions — Email Questions Map
Mapeamento completo de question_id -> texto da pergunta para todas as 6 áreas.
Gerado automaticamente por _s1_build_email_data.py
"""

QUESTION_LABELS = {
    # Supply Chain & Compras
    "sc_01": "Capacidade de previsão de demanda",
    "sc_02": "Visibilidade em tempo real do estoque",
    "sc_03": "Planejamento de compras e reposição de estoque",
    "sc_04": "Integração de dados com fornecedores",
    "sc_05": "Monitoramento de desempenho dos fornecedores",
    "sc_06": "Controle do custo total de aquisição (TCO)",
    "sc_07": "Identificação e gestão de rupturas de estoque",
    "sc_08": "Análise de sazonalidade e tendências em compras",
    "sc_09": "Gestão de estoque de segurança e giro de estoque",
    "sc_10": "Rastreabilidade dos produtos na cadeia",
    "sc_11": "Análise e otimização de custos logísticos",
    "sc_12": "Automação em cotação e negociação com fornecedores",
    "sc_13": "Medição e redução do lead time de compras",
    "sc_14": "Análise de risco na cadeia de suprimentos",
    "sc_15": "Uso de dados para negociar com fornecedores",
    "sc_16": "Integração entre Supply Chain e Vendas/Comercial",
    "sc_17": "Gestão de produtos com baixo giro ou obsoletos",
    "sc_18": "Analytics para otimização do mix de produtos",
    "sc_19": "Monitoramento de qualidade dos produtos recebidos",
    "sc_20": "Maturidade do processo de S&OP",
    "sc_21": "Análise do impacto financeiro das decisões de estoque",
    "sc_22": "Uso de dados externos no planejamento (clima, câmbio)",
    # Inteligência Comercial & RevOps
    "com_01": "Monitoramento e análise do funil de vendas",
    "com_02": "Segmentação de clientes baseada em dados",
    "com_03": "Medição do Custo de Aquisição de Clientes (CAC)",
    "com_04": "Análise do Lifetime Value (LTV) dos clientes",
    "com_05": "Identificação de oportunidades de cross-sell e upsell",
    "com_06": "Previsão de receita (forecast de vendas)",
    "com_07": "Análise e redução do churn",
    "com_08": "Integração entre CRM, marketing e dados financeiros",
    "com_09": "Medição do ROI das campanhas de marketing",
    "com_10": "Personalização das abordagens comerciais",
    "com_11": "Análise de performance do time de vendas",
    "com_12": "Análise de precificação e elasticidade de preço",
    "com_13": "Identificação e priorização de leads",
    "com_14": "Análise do ciclo de vendas e tempo de fechamento",
    "com_15": "Monitoramento de satisfação e NPS dos clientes",
    "com_16": "Análise de mercado e inteligência competitiva",
    "com_17": "Análise de rentabilidade por cliente, produto e canal",
    "com_18": "Automação de follow-up e nutrição de leads",
    "com_19": "Uso de dados para definir territórios e cotas",
    "com_20": "Análise de cohort e retenção de clientes",
    "com_21": "Medição e otimização da velocidade do pipeline",
    "com_22": "Uso de dados para expansão em novos mercados",
    # Crédito & Risco
    "cr_01": "Análise de crédito para novos clientes",
    "cr_02": "Automação no processo de concessão de crédito",
    "cr_03": "Monitoramento do risco da carteira de crédito",
    "cr_04": "Modelos preditivos para risco de inadimplência",
    "cr_05": "Segmentação e priorização da régua de cobrança",
    "cr_06": "Análise de fraude em crédito e pagamento",
    "cr_07": "Cálculo e monitoramento de provisões (PDD)",
    "cr_08": "Integração entre dados de crédito e operacionais",
    "cr_09": "Análise e otimização do limite de crédito",
    "cr_10": "Análise de concentração de risco na carteira",
    "cr_11": "Eficiência e custo do processo de cobrança",
    "cr_12": "Uso de dados alternativos na análise de crédito",
    "cr_13": "Gestão do risco de contraparte em operações B2B",
    "cr_14": "Automação nos processos de recuperação de crédito",
    "cr_15": "Análise do impacto das políticas de crédito",
    "cr_16": "Conformidade e auditabilidade dos processos de crédito",
    "cr_17": "Monitoramento do risco operacional financeiro",
    "cr_18": "Análise de vintage e safra da carteira de crédito",
    "cr_19": "Precificação baseada em risco de crédito",
    "cr_20": "Monitoramento de variáveis macroeconômicas no risco",
    "cr_21": "Gestão do risco de liquidez e fluxo de caixa",
    # Dados & Machine Learning
    "ml_01": "Qualidade e confiabilidade dos dados",
    "ml_02": "Centralização e integração das fontes de dados",
    "ml_03": "Governança e catálogo de dados",
    "ml_04": "Uso de modelos de Machine Learning em produção",
    "ml_05": "Gestão do ciclo de vida dos modelos (MLOps)",
    "ml_06": "Maturidade da infraestrutura de dados",
    "ml_07": "Privacidade e segurança dos dados (LGPD/GDPR)",
    "ml_08": "Democratização do acesso a dados na empresa",
    "ml_09": "Monitoramento de performance dos modelos de ML",
    "ml_10": "Uso de IA generativa e LLMs nos processos",
    "ml_11": "Gestão e documentação de experimentos de dados",
    "ml_12": "Capacitação da equipe em dados e analytics",
    "ml_13": "Explicabilidade e interpretabilidade dos modelos (XAI)",
    "ml_14": "Automação dos pipelines de dados (ETL/ELT)",
    "ml_15": "Medição do ROI dos projetos de dados e ML",
    "ml_16": "Uso de dados em tempo real (streaming)",
    "ml_17": "Estratégia de dados e roadmap analítico",
    "ml_18": "Uso de feature stores e reutilização de features",
    "ml_19": "Testes e validação de modelos antes de produção",
    "ml_20": "Integração entre dados e sistemas de decisão",
    "ml_21": "Cultura data-driven na organização",
    # Automação, RPA & Alertas
    "aut_01": "Percentual de processos repetitivos automatizados",
    "aut_02": "Identificação e priorização de oportunidades de automação",
    "aut_03": "Automação na geração e distribuição de relatórios",
    "aut_04": "Gestão e monitoramento de robôs em produção",
    "aut_05": "Automação de integrações entre sistemas (APIs/ETL)",
    "aut_06": "Alertas inteligentes para monitorar KPIs críticos",
    "aut_07": "Automação em cobrança e comunicação com clientes",
    "aut_08": "Automação de coleta e consolidação de dados",
    "aut_09": "Uso de chatbots e assistentes virtuais",
    "aut_10": "Automação do processo de precificação",
    "aut_11": "Automação em processos de compras e aprovações",
    "aut_12": "Monitoramento e alertas de anomalias em dados",
    "aut_13": "Automação em processos de RH",
    "aut_14": "Automação no monitoramento de concorrentes e mercado",
    "aut_15": "Automação em faturamento e conciliação financeira",
    "aut_16": "Gestão e documentação de processos automatizados",
    "aut_17": "Automação no onboarding de clientes e parceiros",
    "aut_18": "Medição do ROI e ganhos de produtividade das automações",
    "aut_19": "Automação em processos de compliance e auditoria",
    "aut_20": "Uso de automação para melhorar a experiência do cliente",
    "aut_21": "Integração entre automações e sistemas de BI/Analytics",
    # Dashboards & Analytics
    "dash_01": "Qualidade e usabilidade dos dashboards",
    "dash_02": "Atualização e frequência dos dados nos dashboards",
    "dash_03": "Alinhamento dos KPIs com prioridades estratégicas",
    "dash_04": "Nível de self-service analytics na empresa",
    "dash_05": "Medição de adoção e uso dos dashboards",
    "dash_06": "Análise exploratória e descoberta de insights",
    "dash_07": "Gestão do ciclo de vida de relatórios e dashboards",
    "dash_08": "Análise preditiva e prescritiva nos dashboards",
    "dash_09": "Consistência e confiabilidade das métricas",
    "dash_10": "Personalização dos dashboards por perfil de usuário",
    "dash_11": "Storytelling com dados para stakeholders",
    "dash_12": "Análise de causa raiz (root cause analysis)",
    "dash_13": "Analytics de experiência do cliente (CX)",
    "dash_14": "Análise de benchmarking interno e externo",
    "dash_15": "Análise de coorte e segmentação avançada",
    "dash_16": "Análise geoespacial e territorial",
    "dash_17": "Gestão e análise de dados não estruturados",
    "dash_18": "Análise de simulação e cenários (what-if)",
    "dash_19": "Medição de produtividade e eficiência operacional",
    "dash_20": "Integração entre analytics e tomada de decisão",
    "dash_21": "Acessibilidade e disponibilidade dos dashboards",
    "dash_22": "Análise de atribuição e impacto das iniciativas",
}

AREA_LABELS = {
    "supply_chain": "Supply Chain & Compras",
    "comercial": "Inteligência Comercial & RevOps",
    "credito_risco": "Crédito & Risco",
    "dados_ml": "Dados & Machine Learning",
    "automacao": "Automação, RPA & Alertas",
    "dashboards": "Dashboards & Analytics",
}

AREA_ICONS = {
    "supply_chain": "🚚",
    "comercial": "📈",
    "credito_risco": "🛡️",
    "dados_ml": "🧠",
    "automacao": "🤖",
    "dashboards": "📊",
}

RECOMMENDATIONS = {
    "supply_chain": {
        "critico": [
            "Implemente um sistema básico de controle de estoque (ERP ou planilha estruturada) para ter visibilidade mínima dos níveis de estoque em tempo real.",
            "Defina políticas simples de ponto de pedido e estoque de segurança para os 20% de SKUs que representam 80% do seu faturamento (análise ABC).",
            "Crie um processo formal de S&OP mensal com dados históricos de vendas para reduzir compras por urgência e rupturas.",
            "Implemente um scorecard básico de fornecedores com métricas de prazo, qualidade e preço para embasar negociações.",
            "Automatize relatórios diários de estoque crítico e rupturas para que a equipe possa agir proativamente.",
        ],
        "desenvolvimento": [
            "Evolua para modelos estatísticos de previsão de demanda (médias móveis, suavização exponencial) integrados ao seu ERP.",
            "Implemente análise de sazonalidade e tendências para ajustar automaticamente os parâmetros de reposição.",
            "Desenvolva um dashboard de Supply Chain com KPIs em tempo real: giro de estoque, cobertura, fill rate e OTIF.",
            "Integre dados de fornecedores via API ou EDI para reduzir lead times e melhorar a acurácia do planejamento.",
            "Implemente análise de TCO (Custo Total de Aquisição) para decisões de compra mais estratégicas.",
        ],
        "avancado": [
            "Implemente modelos de ML para previsão de demanda com variáveis externas (clima, câmbio, tendências de mercado).",
            "Desenvolva um sistema de reposição automática com parâmetros dinâmicos baseados em variabilidade de demanda e lead time.",
            "Implemente rastreabilidade end-to-end com IoT/RFID para visibilidade completa da cadeia.",
            "Desenvolva análise de risco quantitativa da cadeia com stress tests e planos de contingência automatizados.",
            "Implemente S&OP avançado com simulação de cenários e otimização de portfólio baseada em rentabilidade.",
        ],
    },
    "comercial": {
        "critico": [
            "Implemente um CRM básico para estruturar o funil de vendas e ter visibilidade das oportunidades em andamento.",
            "Defina e calcule métricas fundamentais: CAC, LTV, taxa de conversão por etapa e ciclo médio de vendas.",
            "Crie segmentação básica de clientes por porte, setor e potencial para priorizar esforços comerciais.",
            "Implemente um processo de forecast de vendas mensal com base em histórico e pipeline atual.",
            "Automatize relatórios de performance do time de vendas com metas vs. realizado por vendedor.",
        ],
        "desenvolvimento": [
            "Evolua para segmentação comportamental com análise RFM (Recência, Frequência, Valor) para identificar clientes de alto valor.",
            "Implemente modelos de propensão de churn para identificar clientes em risco antes da perda.",
            "Desenvolva análise de rentabilidade por cliente, produto e canal para focar nos segmentos mais lucrativos.",
            "Implemente lead scoring automático para priorizar os leads com maior probabilidade de conversão.",
            "Integre CRM, marketing e dados financeiros para ter visão 360° do cliente e medir ROI por canal.",
        ],
        "avancado": [
            "Implemente modelos preditivos de LTV e churn com intervenção proativa e personalização em escala.",
            "Desenvolva precificação dinâmica com análise de elasticidade e otimização de margem por segmento.",
            "Implemente análise de atribuição multi-touch para otimizar o mix de canais de marketing.",
            "Desenvolva análise de cohort avançada para identificar padrões de retenção e estratégias de expansão.",
            "Implemente RevOps completo com integração de dados em tempo real e decisões automatizadas no pipeline.",
        ],
    },
    "credito_risco": {
        "critico": [
            "Implemente um processo formal de análise de crédito com consulta a bureaus e critérios mínimos documentados.",
            "Crie uma régua de cobrança básica com comunicações automáticas por e-mail/SMS para diferentes faixas de atraso.",
            "Defina políticas de limite de crédito por perfil de cliente com revisão periódica.",
            "Implemente monitoramento mensal da carteira com indicadores de inadimplência, PDD e concentração.",
            "Documente e automatize o processo de aprovação de crédito com alçadas definidas por valor.",
        ],
        "desenvolvimento": [
            "Desenvolva um scorecard de crédito com variáveis comportamentais e financeiras para decisões mais precisas.",
            "Implemente modelo de propensão à inadimplência para intervenção proativa antes do vencimento.",
            "Evolua a régua de cobrança para segmentação por perfil de risco e canal preferencial de comunicação.",
            "Implemente análise de vintage para identificar padrões de safra e ajustar políticas de concessão.",
            "Desenvolva análise de concentração de risco com limites automáticos por setor, região e cliente.",
        ],
        "avancado": [
            "Implemente modelos de perda esperada (ECL/IFRS 9) para provisões dinâmicas e mais precisas.",
            "Desenvolva detecção de fraude em tempo real com análise comportamental e modelos de ML.",
            "Implemente precificação baseada em risco (risk-based pricing) com modelos de perda esperada.",
            "Desenvolva stress tests automatizados com cenários macroeconômicos e impacto na carteira.",
            "Implemente XAI (Explicabilidade de IA) nos modelos de crédito para conformidade regulatória e auditoria.",
        ],
    },
    "dados_ml": {
        "critico": [
            "Implemente um processo de qualidade de dados com validações básicas e documentação das principais fontes.",
            "Centralize os dados críticos em um repositório único (data warehouse simples ou banco de dados centralizado).",
            "Defina um glossário de negócio com as métricas e KPIs mais importantes para garantir consistência.",
            "Invista em capacitação básica da equipe em SQL e ferramentas de análise de dados.",
            "Implemente pipelines de ETL automatizados para as principais fontes de dados do negócio.",
        ],
        "desenvolvimento": [
            "Evolua para uma arquitetura de data warehouse moderna com camadas bronze/silver/gold e governança.",
            "Implemente seu primeiro modelo de ML em produção com monitoramento básico de performance.",
            "Desenvolva um catálogo de dados com linhagem, ownership e políticas de acesso.",
            "Implemente framework de privacidade e segurança de dados em conformidade com a LGPD.",
            "Democratize o acesso a dados com ferramentas de self-service analytics e treinamento da equipe.",
        ],
        "avancado": [
            "Implemente MLOps completo com CI/CD para modelos, monitoramento de drift e retreinamento automático.",
            "Desenvolva uma feature store centralizada para reutilização de features entre modelos.",
            "Implemente arquitetura de streaming (Kafka/Flink) para casos de uso que exigem dados em tempo real.",
            "Desenvolva framework de XAI para explicabilidade dos modelos e conformidade regulatória.",
            "Implemente IA generativa em processos críticos com governança, avaliação de ROI e gestão de riscos.",
        ],
    },
    "automacao": {
        "critico": [
            "Mapeie os processos mais repetitivos e de maior volume para identificar as melhores oportunidades de automação.",
            "Automatize a geração e distribuição de relatórios recorrentes com ferramentas como Python ou Power Automate.",
            "Implemente alertas básicos por e-mail para KPIs críticos que saem dos limites aceitáveis.",
            "Automatize o processo de coleta e consolidação de dados de múltiplas planilhas e sistemas.",
            "Implemente um workflow básico de aprovações digitais para substituir processos manuais por e-mail.",
        ],
        "desenvolvimento": [
            "Implemente RPA para os processos de maior volume e menor variabilidade (entrada de dados, conciliações).",
            "Desenvolva alertas inteligentes com detecção de anomalias para monitoramento proativo de KPIs.",
            "Automatize integrações entre sistemas via APIs para eliminar retrabalho e erros de digitação.",
            "Implemente jornadas automatizadas de comunicação com clientes (cobrança, onboarding, pós-venda).",
            "Desenvolva um centro de controle de automações com monitoramento em tempo real e alertas de falha.",
        ],
        "avancado": [
            "Implemente automação cognitiva com IA para processos que exigem interpretação de documentos e decisões.",
            "Desenvolva chatbots com IA para atendimento, vendas e suporte com integração completa aos sistemas.",
            "Implemente detecção de anomalias com ML para identificar problemas antes que impactem o negócio.",
            "Desenvolva automação de compliance com monitoramento contínuo e relatórios regulatórios automáticos.",
            "Implemente feedback loop entre automações e analytics para melhoria contínua dos processos.",
        ],
    },
    "dashboards": {
        "critico": [
            "Defina os 5-10 KPIs mais críticos do negócio e crie dashboards simples e confiáveis para monitorá-los.",
            "Implemente uma ferramenta de BI (Power BI, Tableau ou Metabase) para substituir relatórios em planilhas.",
            "Garanta uma fonte única de verdade para as métricas mais importantes, eliminando inconsistências.",
            "Crie um processo de atualização diária automática dos dashboards principais.",
            "Treine a equipe de gestão no uso básico dos dashboards para tomada de decisão baseada em dados.",
        ],
        "desenvolvimento": [
            "Evolua para dashboards interativos com drill-down, filtros e análise exploratória self-service.",
            "Implemente análise de tendências e alertas automáticos quando KPIs saem dos limites esperados.",
            "Desenvolva dashboards personalizados por perfil de usuário (CEO, gerentes, operacional).",
            "Implemente analytics de uso dos dashboards para identificar o que é mais utilizado e o que pode ser descontinuado.",
            "Desenvolva storytelling com dados para comunicar insights de forma clara e orientada à ação.",
        ],
        "avancado": [
            "Implemente análise preditiva e prescritiva integrada aos dashboards para antecipar problemas e recomendar ações.",
            "Desenvolva análise de simulação e cenários (what-if) para suporte à decisão estratégica.",
            "Implemente análise geoespacial avançada para otimização territorial e identificação de oportunidades.",
            "Desenvolva modelos de atribuição causal para medir o impacto real das iniciativas de negócio.",
            "Implemente decision intelligence com dados integrados em todos os processos de decisão da organização.",
        ],
    },
}
